package:
  name: rayopt
  version: 0.1+git{{ environ.get("TRAVIS_TAG", "") }}
  # version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

about:
  home: https://github.com/jordens/rayopt
  license: LGPLv3+
  license_file: COPYING

source:
  path: ../
  # git_url: https://github.com/jordens/rayopt.git

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - scipy
    - pyyaml
    - matplotlib
    - sqlalchemy
    - fastcache
    - requests
    - six
  run:
    - python
    - cython
    - numpy
    - scipy
    - pyyaml
    - matplotlib
    - sqlalchemy
    - fastcache
    - requests
    - six

build:
  # number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  number: {{ environ.get("TRAVIS_BUILD_NUMBER", 0) }}
  # string: {{ environ.get("GIT_BUILD_STR", "") }}

test:
  imports:
    - rayopt
  commands:
    - python -m unittest discover rayopt.test
